// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.25.0
// source: user_list_matches_by_id.proto

package tinder_matching

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListMatchesByIdRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Limit  uint32 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
}

func (x *ListMatchesByIdRequest) Reset() {
	*x = ListMatchesByIdRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_user_list_matches_by_id_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListMatchesByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMatchesByIdRequest) ProtoMessage() {}

func (x *ListMatchesByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_list_matches_by_id_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMatchesByIdRequest.ProtoReflect.Descriptor instead.
func (*ListMatchesByIdRequest) Descriptor() ([]byte, []int) {
	return file_user_list_matches_by_id_proto_rawDescGZIP(), []int{0}
}

func (x *ListMatchesByIdRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ListMatchesByIdRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ListMatchesByIdResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Matches []*User `protobuf:"bytes,1,rep,name=matches,proto3" json:"matches,omitempty"`
}

func (x *ListMatchesByIdResponse) Reset() {
	*x = ListMatchesByIdResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_user_list_matches_by_id_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListMatchesByIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMatchesByIdResponse) ProtoMessage() {}

func (x *ListMatchesByIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_list_matches_by_id_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMatchesByIdResponse.ProtoReflect.Descriptor instead.
func (*ListMatchesByIdResponse) Descriptor() ([]byte, []int) {
	return file_user_list_matches_by_id_proto_rawDescGZIP(), []int{1}
}

func (x *ListMatchesByIdResponse) GetMatches() []*User {
	if x != nil {
		return x.Matches
	}
	return nil
}

var File_user_list_matches_by_id_proto protoreflect.FileDescriptor

var file_user_list_matches_by_id_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x5f, 0x6d, 0x61, 0x74, 0x63,
	0x68, 0x65, 0x73, 0x5f, 0x62, 0x79, 0x5f, 0x69, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x04, 0x75, 0x73, 0x65, 0x72, 0x1a, 0x11, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x73, 0x63, 0x68, 0x65,
	0x6d, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63,
	0x2d, 0x67, 0x65, 0x6e, 0x2d, 0x6f, 0x70, 0x65, 0x6e, 0x61, 0x70, 0x69, 0x76, 0x32, 0x2f, 0x6f,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x7e, 0x0a, 0x16, 0x4c, 0x69, 0x73, 0x74,
	0x4d, 0x61, 0x74, 0x63, 0x68, 0x65, 0x73, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x2f, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x42, 0x16, 0x92, 0x41, 0x13, 0x32, 0x07, 0x75, 0x73, 0x65, 0x72, 0x20, 0x69,
	0x64, 0xd2, 0x01, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x52, 0x06, 0x75, 0x73, 0x65,
	0x72, 0x49, 0x64, 0x12, 0x33, 0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0d, 0x42, 0x1d, 0x92, 0x41, 0x1a, 0x32, 0x18, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x20,
	0x6c, 0x69, 0x6d, 0x69, 0x74, 0x2c, 0x20, 0x64, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x20, 0x31,
	0x30, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x22, 0x59, 0x0a, 0x17, 0x4c, 0x69, 0x73, 0x74,
	0x4d, 0x61, 0x74, 0x63, 0x68, 0x65, 0x73, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x3e, 0x0a, 0x07, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x65, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x55, 0x73, 0x65, 0x72,
	0x42, 0x18, 0x92, 0x41, 0x15, 0x32, 0x13, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x65, 0x73, 0x20, 0x6f,
	0x66, 0x20, 0x74, 0x68, 0x65, 0x20, 0x75, 0x73, 0x65, 0x72, 0x52, 0x07, 0x6d, 0x61, 0x74, 0x63,
	0x68, 0x65, 0x73, 0x42, 0x25, 0x5a, 0x23, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x77, 0x61, 0x79, 0x31, 0x31, 0x32, 0x32, 0x39, 0x2f, 0x74, 0x69, 0x6e, 0x64, 0x65,
	0x72, 0x5f, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x69, 0x6e, 0x67, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_user_list_matches_by_id_proto_rawDescOnce sync.Once
	file_user_list_matches_by_id_proto_rawDescData = file_user_list_matches_by_id_proto_rawDesc
)

func file_user_list_matches_by_id_proto_rawDescGZIP() []byte {
	file_user_list_matches_by_id_proto_rawDescOnce.Do(func() {
		file_user_list_matches_by_id_proto_rawDescData = protoimpl.X.CompressGZIP(file_user_list_matches_by_id_proto_rawDescData)
	})
	return file_user_list_matches_by_id_proto_rawDescData
}

var file_user_list_matches_by_id_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_user_list_matches_by_id_proto_goTypes = []interface{}{
	(*ListMatchesByIdRequest)(nil),  // 0: user.ListMatchesByIdRequest
	(*ListMatchesByIdResponse)(nil), // 1: user.ListMatchesByIdResponse
	(*User)(nil),                    // 2: user.User
}
var file_user_list_matches_by_id_proto_depIdxs = []int32{
	2, // 0: user.ListMatchesByIdResponse.matches:type_name -> user.User
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_user_list_matches_by_id_proto_init() }
func file_user_list_matches_by_id_proto_init() {
	if File_user_list_matches_by_id_proto != nil {
		return
	}
	file_user_schema_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_user_list_matches_by_id_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListMatchesByIdRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_user_list_matches_by_id_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListMatchesByIdResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_user_list_matches_by_id_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_user_list_matches_by_id_proto_goTypes,
		DependencyIndexes: file_user_list_matches_by_id_proto_depIdxs,
		MessageInfos:      file_user_list_matches_by_id_proto_msgTypes,
	}.Build()
	File_user_list_matches_by_id_proto = out.File
	file_user_list_matches_by_id_proto_rawDesc = nil
	file_user_list_matches_by_id_proto_goTypes = nil
	file_user_list_matches_by_id_proto_depIdxs = nil
}
